return {
	name = 'SinisterRectus/discordia',
	version = '2.9.1',
	homepage = '',
	dependencies = {
        "creationix/base64             ",
        "creationix/coro-channel       ",
        "creationix/coro-fs            ",
        "creationix/coro-http          ",
        "creationix/coro-net           ",
        "creationix/coro-websocket     ",
        "creationix/coro-wrapper       ",
        "creationix/mime               ",
        "creationix/pathjoin           ",
        "creationix/sha1               ",
        "creationix/weblit             ",
        "creationix/weblit-app         ",
        "creationix/weblit-auto-headers",
        "creationix/weblit-router      ",
        "creationix/weblit-server      ",
        "creationix/weblit-static      ",
        "creationix/weblit-websocket   ",
        "creationix/websocket-codec    ",
        "luvit/http-codec              ",
        "luvit/json                    ",
        "luvit/querystring             ",
        "luvit/resource                ",
        "luvit/secure-socket           "
    },
	tags = {'discord', 'api'},
	license = 'MIT',
	author = 'Sinister Rectus',
	files = {'**.lua'},
}